const ACTIONS = {
    //
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    LOGOUT: 'LOGOUT',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    LOG_ADMIN: 'LOG_ADMIN',
    OUT_ADMIN: 'OUT_ADMIN',
    // Product
    GET_PRODUCTS: 'GET_PRODUCTS',
    // Cart
    HANDLE_CART: 'HANDLE_CART',
    MINUS_QUANTITY: 'MINUS_QUANTITY',
    PLUS_QUANTITY: 'PLUS_QUANTITY',
    RESET_CART: 'RESET_CART',
    // Order
    CREATE_ORDER: 'CREATE_ORDER',
    // Location
    GET_ALL_PROVINCE: 'GET_ALL_PROVINCE',
    GET_ALL_DISTRICT: 'GET_ALL_DISTRICT',
    GET_ALL_WARD: 'GET_ALL_WARD',
};

export default ACTIONS;
